name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll:4.3.2

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll
        run: jekyll build

      - name: Deploy to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: build
          force_orphan: true
