on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1

    steps:
      - uses: actions/checkout@v4
    
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Acessa servidor e atualiza as coisas
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            cd teste_2
            git pull origin build
          EOF
