name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ime.usp.br >> ~/.ssh/known_hosts
          
      - name: Rodar git pull na máquina remota
        run: |
          ssh semap@ime.usp.br 'mkdir teste_github'
# ssh oapotalej@ime.usp.br 'cd teste_2 && rm -r -f jekyll_teste && git clone https://github.com/Potalej/jekyll_teste.git -b build jekyll_teste'
          
